/**
 * Curated retreat listings. Affiliates: BookSurfCamps aid=11528; BookYogaRetreats ref in each listing URL.
 * Cover images: local /public/retreats/{listing-id}.jpg (sourced from Unsplash & Pexels;
 * partner listing pages may be protected for automated image extraction).
 */
export const BOOKSURFCAMPS_AID = "11528";

export type RetreatCategory = "surf" | "yoga";

export type RetreatTypeFacet = "surf-camp" | "surf-yoga" | "kitesurf" | "yoga-retreat";

export type RetreatPartner = "booksurfcamps" | "bookyogaretreats";

export type RetreatListing = {
  id: string;
  category: RetreatCategory;
  retreatTypes: RetreatTypeFacet[];
  regionSlug: string;
  country: string;
  title: string;
  organizer: string;
  location: string;
  href: string;
  coverImage: string;
  coverImageAlt: string;
  badge?: string;
  bullets: string[];
  priceNote?: string;
  priceFromEur?: number;
  /** Booking site for CTA copy; defaults to BookSurfCamps. */
  partner?: RetreatPartner;
};

const aid = `aid=${BOOKSURFCAMPS_AID}`;

export const retreatCatalog: RetreatListing[] = [
  {
    id: "harmony-surf-lodge",
    category: "surf",
    retreatTypes: ["surf-camp"],
    regionSlug: "imi-ouaddar",
    country: "Morocco",
    title: "7-day premium surf coaching retreat",
    organizer: "Harmony Surf Lodge",
    location: "Imi Ouaddar, near Taghazout",
    coverImage: "/retreats/harmony-surf-lodge.jpg",
    coverImageAlt: "Surfer on a wave in Morocco near the Atlantic coast",
    href: `https://www.booksurfcamps.com/harmony-surf-lodge/7-day-premium-surf-coaching-retreat-in-imi-ouaddar-near-taghazout-morocco?${aid}`,
    badge: "Among the 10 most popular in Africa & Middle East",
    bullets: [
      "Max 8 guests · English instruction · beginner & intermediate",
      "6 nights full board, 5 surf lessons + supervised free surf, gear & daily transport",
      "Agadir (AGA) airport transfer included · evening photo & video debrief",
    ],
    priceNote:
      "Indicative from €455 (shared room, 1 person) — confirm dates and room type on BookSurfCamps.",
    priceFromEur: 455,
  },
  {
    id: "crocro-surf-maroc",
    category: "surf",
    retreatTypes: ["surf-camp", "surf-yoga"],
    regionSlug: "tamraght",
    country: "Morocco",
    title: "7-day yoga & surf retreat",
    organizer: "Crocro Surf Maroc",
    location: "Tamraght, Taghazout bay",
    coverImage: "/retreats/crocro-surf-maroc.jpg",
    coverImageAlt: "Outdoor yoga in a peaceful natural setting at sunrise",
    href: `https://www.booksurfcamps.com/crocro-surf-maroc/7-day-yoga-and-surf-retreat-in-tamraght?${aid}`,
    badge: "Top 10% most popular on BookSurfCamps",
    bullets: [
      "5 days surf + 5 days yoga · certified surf instruction · surf photo & video",
      "All levels · max 15 · full board · boards & wetsuits · 6 nights",
      "Optional airport transfer — confirm on BookSurfCamps",
    ],
    priceNote: "See live EUR pricing on BookSurfCamps.",
  },
  {
    id: "paddle-out-morocco",
    category: "surf",
    retreatTypes: ["surf-yoga"],
    regionSlug: "tamraght",
    country: "Morocco",
    title: "7-day surf & yoga with beginner coaching",
    organizer: "Paddle Out Morocco",
    location: "Tamraght",
    coverImage: "/retreats/paddle-out-morocco.jpg",
    coverImageAlt: "Turquoise shoreline and sandy beach",
    href: `https://www.booksurfcamps.com/paddle-out-morocco/7-day-surf-and-yoga-package-with-personalized-beginner-surf-coaching-in-tamraght-morocco?${aid}`,
    bullets: [
      "Personalized beginner surf coaching",
      "Taghazout-area base — classic Morocco Atlantic surf",
      "See inclusions and transfers on BookSurfCamps",
    ],
    priceNote: "Confirm pricing on BookSurfCamps.",
  },
  {
    id: "paddle-out-morocco-8",
    category: "yoga",
    retreatTypes: ["surf-yoga"],
    regionSlug: "tamraght",
    country: "Morocco",
    title: "8-day surf & yoga with personalized beginner coaching",
    organizer: "Paddle Out Morocco",
    location: "Tamraght",
    coverImage: "/retreats/paddle-out-morocco-8.jpg",
    coverImageAlt: "Coastal bay with clear water",
    href: `https://www.booksurfcamps.com/paddle-out-morocco/8-day-surf-and-yoga-personalized-surf-coaching-for-beginner-surfers-in-tamraght?${aid}`,
    bullets: [
      "Eight days · surf and yoga · coaching for beginners",
      "Tamraght base near Taghazout",
      "Full details on BookSurfCamps",
    ],
    priceNote: "Confirm pricing on BookSurfCamps.",
  },
  {
    id: "atlanticzin-kitesurf",
    category: "surf",
    retreatTypes: ["kitesurf"],
    regionSlug: "essaouira",
    country: "Morocco",
    title: "8-day kitesurf camp (beginner or intermediate)",
    organizer: "Atlanticzin Watersports",
    location: "Essaouira area (Marrakesh–Safi)",
    coverImage: "/retreats/atlanticzin-kitesurf.jpg",
    coverImageAlt: "Person windsurfing on bright blue coastal water",
    href: `https://www.booksurfcamps.com/atlanticzin-watersports/8-day-beginner-or-intermediate-pack-kitesurf-camp-in-essaouira-marrakesh-safi?${aid}`,
    bullets: [
      "Kitesurfing progression in Essaouira wind conditions",
      "Beginner or intermediate track",
      "Equipment and pack details on BookSurfCamps",
    ],
    priceNote: "Confirm pricing on BookSurfCamps.",
  },
  {
    id: "marias-hostel-porto",
    category: "surf",
    retreatTypes: ["surf-camp"],
    regionSlug: "porto",
    country: "Portugal",
    title: "6-day nature surfcamp",
    organizer: "Maria's Hostel Surf",
    location: "Porto, North Portugal",
    coverImage: "/retreats/marias-hostel-porto.jpg",
    coverImageAlt: "Rocky Atlantic coastline in Portugal",
    href: `https://www.booksurfcamps.com/marias-hostel-surf/6-day-nature-surfcamp-in-porto-north-portugal?${aid}`,
    bullets: ["Nature-focused surf camp · North Portugal", "6 days — see schedule on listing", "Confirm transfers and level on BookSurfCamps"],
    priceNote: "Confirm pricing on BookSurfCamps.",
  },
  {
    id: "peniche-surf-lodge-safari",
    category: "surf",
    retreatTypes: ["surf-camp"],
    regionSlug: "peniche",
    country: "Portugal",
    title: "7-day affordable surf safari",
    organizer: "Peniche Surf Lodge",
    location: "Peniche, Portugal",
    coverImage: "/retreats/peniche-surf-lodge-safari.jpg",
    coverImageAlt: "Surfer riding a wave",
    href: `https://www.booksurfcamps.com/peniche-surf-lodge-1/7-day-affordable-surf-safari-5-in-water-coaching-sessions-daily-rental-with-guidance-in-portugal?${aid}`,
    bullets: [
      "5 in-water coaching sessions · daily rental with guidance",
      "Affordable week in Peniche",
      "See full inclusions on BookSurfCamps",
    ],
    priceNote: "Confirm pricing on BookSurfCamps.",
  },
  {
    id: "haleiwa-surf-yoga-oahu",
    category: "surf",
    retreatTypes: ["surf-yoga"],
    regionSlug: "oahu",
    country: "USA",
    title: "5-day all-inclusive surf, yoga & adventure (North Shore, Oahu)",
    organizer: "Haleiwa Surf and Yoga Retreats",
    location: "North Shore, Oahu, Hawaii",
    coverImage: "/retreats/haleiwa-surf-yoga-oahu.jpg",
    coverImageAlt: "Tropical beach and turquoise water from above",
    href: `https://www.booksurfcamps.com/haleiwa-surf-and-yoga-retreats/5-day-all-inclusive-surf-yoga-and-adventure-holiday-on-the-north-shore-of-oahu-hawaii?${aid}`,
    bullets: ["All-inclusive · surf, yoga, adventure", "North Shore, Oahu", "Dates and pack on BookSurfCamps"],
    priceNote: "Confirm pricing on BookSurfCamps.",
  },
  {
    id: "surf-experience-lagos",
    category: "surf",
    retreatTypes: ["surf-camp"],
    regionSlug: "lagos",
    country: "Portugal",
    title: "5-day refreshing surf camp",
    organizer: "The Surf Experience",
    location: "Lagos, Portugal",
    coverImage: "/retreats/surf-experience-lagos.jpg",
    coverImageAlt: "Sandy beach and ocean horizon",
    href: `https://www.booksurfcamps.com/the-surf-experience/5-days-refreshing-surf-camp-in-lagos-portugal?${aid}`,
    bullets: ["Refreshing surf week in Lagos", "Algarve coast", "See listing for level and inclusions"],
    priceNote: "Confirm pricing on BookSurfCamps.",
  },
  {
    id: "golden-waves-porto",
    category: "yoga",
    retreatTypes: ["surf-yoga"],
    regionSlug: "porto-beach",
    country: "Portugal",
    title: "3-day fluidity eco surf camp",
    organizer: "Golden Waves Surf and Yoga Lodge",
    location: "Porto beach area, Portugal",
    coverImage: "/retreats/golden-waves-porto.jpg",
    coverImageAlt: "Yoga and wellness outdoors",
    href: `https://www.booksurfcamps.com/golden-waves-surf-and-yoga-lodge-portugal/3-days-fluidity-eco-surf-camp-at-porto-beach-paradise-portugal?${aid}`,
    bullets: ["Short eco surf camp · surf & yoga lodge", "Porto beach paradise", "Details on BookSurfCamps"],
    priceNote: "Confirm pricing on BookSurfCamps.",
  },
  {
    id: "surfers-paradise-weligama",
    category: "surf",
    retreatTypes: ["surf-camp"],
    regionSlug: "weligama",
    country: "Sri Lanka",
    title: "7-day intensive surf class",
    organizer: "Surfers Paradise Weligama",
    location: "Weligama, Sri Lanka",
    coverImage: "/retreats/surfers-paradise-weligama.jpg",
    coverImageAlt: "Tropical beach and palm trees",
    href: `https://www.booksurfcamps.com/surfers-paradise-weligama/7-day-intensive-surf-class-weligama-sri-lanka?${aid}`,
    bullets: ["Intensive surf week · Weligama", "Southern Sri Lanka", "Level and dates on BookSurfCamps"],
    priceNote: "Confirm pricing on BookSurfCamps.",
  },
  {
    id: "kite-buen-hombre-cabarete",
    category: "yoga",
    retreatTypes: ["surf-camp", "surf-yoga", "kitesurf"],
    regionSlug: "cabarete",
    country: "Dominican Republic",
    title: "7-day surf, kitesurf, wing foil & yoga retreat",
    organizer: "Kite Buen Hombre",
    location: "Cabarete area",
    coverImage: "/retreats/kite-buen-hombre-cabarete.jpg",
    coverImageAlt: "Windsurfing on blue water",
    href: `https://www.booksurfcamps.com/kite-buen-hombre/7-day-surf-kitesurf-wing-foil-camp-and-yoga-retreat-in-cabarete?${aid}`,
    bullets: ["Surf · kitesurf · wing foil · yoga", "Caribbean wind-sports hub", "Full program on BookSurfCamps"],
    priceNote: "Confirm pricing on BookSurfCamps.",
  },
  {
    id: "surfcamp-360-santa-cruz",
    category: "surf",
    retreatTypes: ["surf-yoga"],
    regionSlug: "santa-cruz-pt",
    country: "Portugal",
    title: "8-day surfing and yoga holiday",
    organizer: "Surfcamp 360",
    location: "Santa Cruz, Portugal",
    coverImage: "/retreats/surfcamp-360-santa-cruz.jpg",
    coverImageAlt: "Atlantic cliffs and coastline",
    href: `https://www.booksurfcamps.com/surfcamp-360/8-days-surfing-and-yoga-holiday-in-santa-cruz-portugal?${aid}`,
    bullets: ["Surfing and yoga holiday · 8 days", "Santa Cruz, Portugal", "Accommodation and schedule on listing"],
    priceNote: "Confirm pricing on BookSurfCamps.",
  },
  {
    id: "paddle-out-morocco-6-rejuvenating",
    category: "surf",
    retreatTypes: ["surf-yoga"],
    regionSlug: "tamraght",
    country: "Morocco",
    title: "6-day rejuvenating surf & yoga holiday",
    organizer: "Paddle Out Morocco",
    location: "Tamraght, Taghazout",
    coverImage: "/retreats/paddle-out-morocco-6-rejuvenating.jpg",
    coverImageAlt: "Turquoise shoreline and sandy beach",
    href: `https://www.booksurfcamps.com/paddle-out-morocco/6-day-rejuvenating-surf-and-yoga-holiday-in-tamraght-taghazout?${aid}`,
    bullets: ["Six days · surf and yoga · Tamraght–Taghazout", "Rejuvenating pace — see schedule on listing", "Confirm inclusions on BookSurfCamps"],
    priceNote: "Confirm pricing on BookSurfCamps.",
  },
  {
    id: "crocro-surf-maroc-8-agadir",
    category: "surf",
    retreatTypes: ["surf-yoga"],
    regionSlug: "agadir",
    country: "Morocco",
    title: "8-day yoga & surf camp (Agadir area)",
    organizer: "Crocro Surf Maroc",
    location: "Agadir area",
    coverImage: "/retreats/crocro-surf-maroc-8-agadir.jpg",
    coverImageAlt: "Outdoor yoga in a peaceful natural setting at sunrise",
    href: `https://www.booksurfcamps.com/crocro-surf-maroc/8-day-unforgettable-yoga-and-surf-camp-agadir?${aid}`,
    bullets: ["Eight-day surf & yoga camp", "Morocco Atlantic coast", "Dates and pack on BookSurfCamps"],
    priceNote: "Confirm pricing on BookSurfCamps.",
  },
  {
    id: "fu-space-hostel-tamraght",
    category: "surf",
    retreatTypes: ["surf-yoga"],
    regionSlug: "tamraght",
    country: "Morocco",
    title: "7-day surf & yoga — lessons, adventure & culture",
    organizer: "Fu Space Hostel",
    location: "Tamraght, Morocco",
    coverImage: "/retreats/fu-space-hostel-tamraght.jpg",
    coverImageAlt: "Atlantic beach and coastal hills in Morocco",
    href: `https://www.booksurfcamps.com/fu-space-hostel/7-day-lessons-adventure-and-culture-surf-and-yoga-experience-in-tamraght-morocco?${aid}`,
    bullets: ["Surf & yoga week with local adventure", "Tamraght base", "Full program on BookSurfCamps"],
    priceNote: "Confirm pricing on BookSurfCamps.",
  },
  {
    id: "marias-hostel-surf-8-ovar",
    category: "surf",
    retreatTypes: ["surf-camp"],
    regionSlug: "ovar-aveiro",
    country: "Portugal",
    title: "8-day all-levels nature surf camp",
    organizer: "Maria's Hostel Surf",
    location: "Ovar, Aveiro",
    coverImage: "/retreats/marias-hostel-surf-8-ovar.jpg",
    coverImageAlt: "Atlantic dunes and shoreline in Portugal",
    href: `https://www.booksurfcamps.com/marias-hostel-surf/8-days-all-levels-nature-surf-camp-in-ovar-aveiro-portugal?${aid}`,
    bullets: ["Nature surf camp · all levels", "Ovar / Aveiro coast", "Schedule and transfers on BookSurfCamps"],
    priceNote: "Confirm pricing on BookSurfCamps.",
  },
  {
    id: "atlanticzin-kitesurf-6-essaouira",
    category: "surf",
    retreatTypes: ["kitesurf"],
    regionSlug: "essaouira",
    country: "Morocco",
    title: "6-day kitesurf camp (beginner or intermediate)",
    organizer: "Atlanticzin Watersports",
    location: "Essaouira area (Marrakesh–Safi)",
    coverImage: "/retreats/atlanticzin-kitesurf-6-essaouira.jpg",
    coverImageAlt: "Kitesurfing on Moroccan Atlantic coast",
    href: `https://www.booksurfcamps.com/atlanticzin-watersports/6-day-beginner-or-intermediate-kitesurf-camp-in-essaouira-marrakesh-safi?${aid}`,
    bullets: ["Six-day kitesurf progression", "Essaouira wind conditions", "Pack details on BookSurfCamps"],
    priceNote: "Confirm pricing on BookSurfCamps.",
  },
  {
    id: "surf-maroc-6-tamraght",
    category: "surf",
    retreatTypes: ["surf-yoga"],
    regionSlug: "tamraght",
    country: "Morocco",
    title: "6-day beginner surf & yoga camp",
    organizer: "Surf Maroc",
    location: "Tamraght",
    coverImage: "/retreats/surf-maroc-6-tamraght.jpg",
    coverImageAlt: "Surf lineup on a Moroccan beach",
    href: `https://www.booksurfcamps.com/surf-maroc/6-day-beginner-surf-and-yoga-camp-in-tamraght?${aid}`,
    bullets: ["Beginner-focused surf & yoga", "Tamraght base", "See inclusions on BookSurfCamps"],
    priceNote: "Confirm pricing on BookSurfCamps.",
  },
  {
    id: "marias-hostel-surf-6-ovar",
    category: "surf",
    retreatTypes: ["surf-camp"],
    regionSlug: "ovar-aveiro",
    country: "Portugal",
    title: "6-day all-levels nature surf camp",
    organizer: "Maria's Hostel Surf",
    location: "Ovar, Aveiro",
    coverImage: "/retreats/marias-hostel-surf-6-ovar.jpg",
    coverImageAlt: "Open beach and dunes in Northern Portugal",
    href: `https://www.booksurfcamps.com/marias-hostel-surf/6-days-all-levels-nature-surf-camp-in-ovar-aveiro-portugal?${aid}`,
    bullets: ["Nature surf camp · all levels", "Six days · Ovar / Aveiro", "Confirm level and dates on BookSurfCamps"],
    priceNote: "Confirm pricing on BookSurfCamps.",
  },
  {
    id: "anamarsurfmorocco-5-tamraght",
    category: "surf",
    retreatTypes: ["surf-camp"],
    regionSlug: "tamraght",
    country: "Morocco",
    title: "5-day surf coaching — catch the wave",
    organizer: "Anamar Surf Morocco",
    location: "Tamraght",
    coverImage: "/retreats/anamarsurfmorocco-5-tamraght.jpg",
    coverImageAlt: "Surfer paddling out on a Moroccan point break",
    href: `https://www.booksurfcamps.com/anamarsurfmorocco/5-day-catch-the-wave-of-a-lifetime-through-surf-coaching-in-tamraght-morocco?${aid}`,
    bullets: ["Focused surf coaching · five days", "Tamraght", "Coach ratio and gear on BookSurfCamps"],
    priceNote: "Confirm pricing on BookSurfCamps.",
  },
  {
    id: "hola-surf-5-tamraght",
    category: "surf",
    retreatTypes: ["surf-camp"],
    regionSlug: "tamraght",
    country: "Morocco",
    title: "5-day all-inclusive surf coaching",
    organizer: "Hola Surf",
    location: "Tamraght, Agadir area",
    coverImage: "/retreats/hola-surf-5-tamraght.jpg",
    coverImageAlt: "Warm Atlantic waves near Tamraght",
    href: `https://www.booksurfcamps.com/hola-surf/5-day-all-inclusive-surf-coaching-in-tamraght-agadir?${aid}`,
    bullets: ["All-inclusive surf coaching · five days", "Tamraght / Agadir area", "See pack on BookSurfCamps"],
    priceNote: "Confirm pricing on BookSurfCamps.",
  },
  {
    id: "sand-surf-morocco-5",
    category: "surf",
    retreatTypes: ["surf-camp"],
    regionSlug: "tamraght",
    country: "Morocco",
    title: "5-day fluidity eco surf camp",
    organizer: "Sand Surf Morocco",
    location: "Tamraght",
    coverImage: "/retreats/sand-surf-morocco-5.jpg",
    coverImageAlt: "Sandy beach and rolling surf",
    href: `https://www.booksurfcamps.com/sand-surf-morocco/5-day-fluidity-eco-surf-camp-in-tamraght?${aid}`,
    bullets: ["Eco-minded surf camp · fluidity focus", "Tamraght", "Listing details on BookSurfCamps"],
    priceNote: "Confirm pricing on BookSurfCamps.",
  },
  {
    id: "reborn-surf-camp-7",
    category: "surf",
    retreatTypes: ["surf-camp"],
    regionSlug: "tamraght",
    country: "Morocco",
    title: "7-day surf camp",
    organizer: "Reborn Surf Camp",
    location: "Tamraght",
    coverImage: "/retreats/reborn-surf-camp-7.jpg",
    coverImageAlt: "Surf camp group on the beach",
    href: `https://www.booksurfcamps.com/reborn-surf-camp/7-day-surf-camp-in-tamraght?${aid}`,
    bullets: ["Week-long surf camp", "Classic Taghazout-area waves", "Level and dates on BookSurfCamps"],
    priceNote: "Confirm pricing on BookSurfCamps.",
  },
  {
    id: "harmony-surf-lodge-5",
    category: "surf",
    retreatTypes: ["surf-camp"],
    regionSlug: "imi-ouaddar",
    country: "Morocco",
    title: "5-day surf retreat (all levels)",
    organizer: "Harmony Surf Lodge",
    location: "Imi Ouaddar, near Taghazout",
    coverImage: "/retreats/harmony-surf-lodge-5.jpg",
    coverImageAlt: "Surfer on a wave in Morocco near the Atlantic coast",
    href: `https://www.booksurfcamps.com/harmony-surf-lodge/5-day-surf-retreat-experience-for-all-levels-in-imi-ouaddar-taghazout-morocco?${aid}`,
    bullets: ["Five-day surf retreat · all levels", "Imi Ouaddar", "Confirm room and transfers on BookSurfCamps"],
    priceNote: "Confirm pricing on BookSurfCamps.",
  },
  {
    id: "let-us-surf-7-budget",
    category: "surf",
    retreatTypes: ["surf-camp"],
    regionSlug: "taghazout-region",
    country: "Morocco",
    title: "7-day budget surf escape",
    organizer: "Let Us Surf",
    location: "Taghazout region",
    coverImage: "/retreats/let-us-surf-7-budget.jpg",
    coverImageAlt: "Moroccan coastline near Taghazout",
    href: `https://www.booksurfcamps.com/let-us-surf/7-day-budget-surf-escape-in-taghazout-region?${aid}`,
    bullets: ["Budget-friendly surf week", "Taghazout region", "See what's included on BookSurfCamps"],
    priceNote: "Confirm pricing on BookSurfCamps.",
  },
  {
    id: "easy-surf-maroc-8",
    category: "surf",
    retreatTypes: ["surf-yoga"],
    regionSlug: "tamraght",
    country: "Morocco",
    title: "8-day surf & yoga retreat",
    organizer: "Easy Surf Maroc",
    location: "Morocco (Atlantic coast)",
    coverImage: "/retreats/easy-surf-maroc-8.jpg",
    coverImageAlt: "Sunset over the Atlantic in Morocco",
    href: `https://www.booksurfcamps.com/easy-surf-maroc/8-days-outstanding-surf-and-yoga-retreat-in-morocco?${aid}`,
    bullets: ["Eight-day surf & yoga", "Morocco Atlantic surf", "Full itinerary on BookSurfCamps"],
    priceNote: "Confirm pricing on BookSurfCamps.",
  },
  {
    id: "let-us-surf-5-relax",
    category: "surf",
    retreatTypes: ["surf-yoga"],
    regionSlug: "tamraght",
    country: "Morocco",
    title: "5-day surf & relax (all levels)",
    organizer: "Let Us Surf",
    location: "Tamraght",
    coverImage: "/retreats/let-us-surf-5-relax.jpg",
    coverImageAlt: "Calm bay and surf break in Tamraght",
    href: `https://www.booksurfcamps.com/let-us-surf/5-day-surf-and-relax-experience-perfect-for-all-levels-in-tamraght?${aid}`,
    bullets: ["Surf & relax · five days · all levels", "Tamraght", "Dates and pack on BookSurfCamps"],
    priceNote: "Confirm pricing on BookSurfCamps.",
  },
  {
    id: "bookyoga-sedona-unwind-rewild",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "sedona",
    country: "USA",
    title: "4-day unwind & rewild women's wellness retreat",
    organizer: "Retreats and More",
    location: "Sedona, Arizona",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Red rock desert landscape near Sedona at golden hour",
    href: "https://www.bookyogaretreats.com/retreats-and-more/4-day-unwind-and-rewild-women-s-wellness-retreat-in-sedona-usa?ref=627324",
    partner: "bookyogaretreats",
    bullets: [
      "Women's wellness · Sedona red-rock setting",
      "Yoga, nature, and reset — see full schedule on the listing",
      "Confirm dates and inclusions on BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-alicante-refreshing-yoga",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "alicante",
    country: "Spain",
    title: "4-day refreshing yoga retreat",
    organizer: "La Crisalida Retreats",
    location: "Alicante, Costa Blanca, Valencia",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Mediterranean coast and calm sea near Alicante",
    href: "https://www.bookyogaretreats.com/la-crisalida-retreats/4-day-refreshing-yoga-retreat-in-alicante-costa-blanca-valencia?ref=627337",
    partner: "bookyogaretreats",
    bullets: [
      "Short coastal yoga break · Costa Blanca",
      "Wellness-focused pace — details on the listing",
      "Confirm room and meals on BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-goa-ayurvedic",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "goa",
    country: "India",
    title: "7-day wellness & rejuvenation (yoga, Ayurveda, meditation)",
    organizer: "Preksha Yoga Ashram",
    location: "Goa",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Tropical greenery and quiet space for yoga and meditation",
    href: "https://www.bookyogaretreats.com/preksha-yoga-ashram/7-day-wellness-and-rejuvenation-retreat-with-yoga-ayurvedic-massages-and-meditation-in-goa?ref=627343",
    partner: "bookyogaretreats",
    bullets: [
      "Yoga, Ayurvedic massages, meditation",
      "Week-long rejuvenation in Goa",
      "Full program on BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-bali-watukaru",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "bali",
    country: "Indonesia",
    title: "3-day Balinese Watukaru yoga awakening",
    organizer: "BaliReal Retreats",
    location: "Bali",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Lush tropical landscape in Bali",
    href: "https://www.bookyogaretreats.com/balireal-retreats/3-day-balinese-watukaru-yoga-awakening-hindu-culture-wellness-nature-retreat-in-bali?ref=627357",
    partner: "bookyogaretreats",
    bullets: [
      "Balinese yoga, culture, wellness, nature",
      "Compact three-day immersion",
      "See inclusions on BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-kampot-how-are-you",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "kampot",
    country: "Cambodia",
    title: '7-day "How are you, really?" yoga retreat',
    organizer: "Yoga Barn Kampot",
    location: "Kampot",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Riverside greenery in Kampot",
    href: "https://www.bookyogaretreats.com/yoga-barn-kampot/7-day-how-are-you-really-yoga-retreat-in-beautiful-kampot?ref=627366",
    partner: "bookyogaretreats",
    bullets: [
      "Week-long yoga retreat in Kampot",
      "Slow travel and practice — check schedule on listing",
      "Book via BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-vallemaggia-nature-yoga",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "vallemaggia",
    country: "Switzerland",
    title: "6-day nature, waterfalls & yoga holiday",
    organizer: "Margaretha van den Broek",
    location: "Vallemaggia, Ticino",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Alpine valley with forest and water in Ticino",
    href: "https://www.bookyogaretreats.com/margaretha-van-den-broek/6-day-nature-waterfalls-and-yoga-holiday-in-vallemaggia-ticino?ref=627378",
    partner: "bookyogaretreats",
    bullets: [
      "Nature, waterfalls, and yoga in Vallemaggia",
      "Ticino mountain setting",
      "Details on BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-peneda-geres-hiking-yoga",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "peneda-geres",
    country: "Portugal",
    title: "8-day hiking & yoga holiday",
    organizer: "Ecotura",
    location: "Peneda-Gerês National Park",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Green hills and trails in northern Portugal",
    href: "https://www.bookyogaretreats.com/ecotura/8-day-hiking-and-yoga-holiday-in-peneda-geres-national-park?ref=6273",
    partner: "bookyogaretreats",
    bullets: [
      "Hiking and yoga in Peneda-Gerês",
      "National park setting — see difficulty on listing",
      "Confirm pack on BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-torre-horadada-beach-yoga",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "torre-de-la-horadada",
    country: "Spain",
    title: "5-day beach, coastal hikes & yoga holiday",
    organizer: "Sun Salute Retreats",
    location: "Torre de la Horadada",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Mediterranean beach and calm sea in Spain",
    href: "https://www.bookyogaretreats.com/sun-salute-retreats/5-day-beach-coastal-hikes-and-yoga-holiday-in-torre-de-la-horadada-spain?ref=6273",
    partner: "bookyogaretreats",
    bullets: [
      "Beach, coastal walks, and yoga",
      "Costa Blanca south — Torre de la Horadada",
      "See dates on BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-wonderland-koh-phangan-5-vegan",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "ko-pha-ngan",
    country: "Thailand",
    title: "5-day vegan wellness retreat (yoga, meditation & more)",
    organizer: "Wonderland Healing Center",
    location: "Ko Pha Ngan, Surat Thani",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Tropical island greenery and calm light in Thailand",
    href: "https://www.bookyogaretreats.com/wonderland-healing-center/5-days-vegan-wellness-retreat-with-yoga-meditation-and-more-in-ko-pha-ngan-surat-thani?ref=6273",
    partner: "bookyogaretreats",
    bullets: [
      "Vegan wellness · yoga and meditation",
      "Koh Phangan setting — see full program on listing",
      "Confirm dates on BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-hilltop-phuket-4-sunrise",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "phuket",
    country: "Thailand",
    title: "4-day yoga holiday with panoramic sunrise yoga",
    organizer: "Hilltop Wellness Resort",
    location: "Phuket",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Hills and morning sky over Phuket",
    href: "https://www.bookyogaretreats.com/hilltop-wellness-resort/4-day-yoga-holiday-with-panoramic-sunrise-yoga-in-phuket?ref=6273",
    partner: "bookyogaretreats",
    bullets: [
      "Sunrise-focused yoga · hilltop resort",
      "Short Phuket break — details on listing",
      "Book via BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-muay-thai-yoga-8-thailand",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "thailand",
    country: "Thailand",
    title: "8-day Muay Thai, yoga, meditation & fitness (all-inclusive)",
    organizer: "Muay Thai Battle Conquer Gym",
    location: "Thailand",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Training and movement in a tropical setting",
    href: "https://www.bookyogaretreats.com/muay-thai-battle-conquer-gym/8-day-muay-thai-yoga-meditation-fitness-combination-all-inclusive-thailand?ref=6273",
    partner: "bookyogaretreats",
    bullets: [
      "Muay Thai, yoga, meditation, and fitness combined",
      "All-inclusive — confirm venue and transfers on listing",
      "See full inclusions on BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-ananda-koh-phangan-4",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "ko-pha-ngan",
    country: "Thailand",
    title: "4-day rejuvenating yoga retreat",
    organizer: "Ananda Yoga Detox Center",
    location: "Koh Phangan",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Quiet tropical setting for yoga and rest",
    href: "https://www.bookyogaretreats.com/ananda-yoga-detox-center/4-day-rejuvenating-yoga-retreat-in-koh-phangan-1?ref=6273",
    partner: "bookyogaretreats",
    bullets: [
      "Short rejuvenating yoga stay",
      "Koh Phangan — detox and yoga focus on listing",
      "Confirm schedule on BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-ccs-hideaway-4-thailand",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "thailand",
    country: "Thailand",
    title: "4-day yoga holiday",
    organizer: "CCS Hideaway",
    location: "Thailand",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Tropical resort pool and palms in Thailand",
    href: "https://www.bookyogaretreats.com/ccs-hideaway/4-days-yoga-holiday-in-thailand?ref=6273",
    partner: "bookyogaretreats",
    bullets: [
      "Four-day yoga holiday with CCS Hideaway",
      "Confirm exact location and room on listing",
      "Details on BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-ccs-hideaway-7-karon-phuket",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "phuket",
    country: "Thailand",
    title: "7-day yoga holiday in Karon",
    organizer: "CCS Hideaway",
    location: "Karon, Phuket",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Beach and coastline in Phuket",
    href: "https://www.bookyogaretreats.com/ccs-hideaway/7-day-yoga-holiday-in-karon-phuket?ref=6273",
    partner: "bookyogaretreats",
    bullets: [
      "Week-long yoga holiday · Karon area",
      "Phuket coast — see accommodation on listing",
      "Book via BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-wonderland-koh-phangan-12-meditation",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "ko-pha-ngan",
    country: "Thailand",
    title: "12-day meditation & yoga retreat",
    organizer: "Wonderland Healing Center",
    location: "Ko Pha Ngan, Thailand",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Island nature and space for long-form retreat",
    href: "https://www.bookyogaretreats.com/wonderland-healing-center/12-days-meditation-and-yoga-retreat-in-ko-pha-ngan-thailand?ref=6273",
    partner: "bookyogaretreats",
    bullets: [
      "Extended meditation and yoga immersion",
      "Koh Phangan — twelve-day format",
      "Full syllabus on BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-paula-nusa-lembongan-4",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "nusa-lembongan",
    country: "Indonesia",
    title: "4-day island yoga holiday",
    organizer: "Paula Eveans Island Garden Huts Yoga",
    location: "Nusa Lembongan",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Tropical island coast and calm water in Indonesia",
    href: "https://www.bookyogaretreats.com/paula-eveans-island-garden-huts-yoga/4-day-island-yoga-holiday-in-nusa-lembongan-indonesia?ref=6273",
    partner: "bookyogaretreats",
    bullets: [
      "Island yoga break off Bali",
      "Garden-hut setting — see inclusions on listing",
      "Book via BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-bali-green-6-wellness",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "bali",
    country: "Indonesia",
    title: "6-day wellness retreat (yoga, detox, spa, meditation & Hindu blessing)",
    organizer: "Bali Green Retreat",
    location: "Bali",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Lush tropical greenery in Bali",
    href: "https://www.bookyogaretreats.com/bali-green-retreat/6-day-wellness-retreat-with-yoga-detox-spa-meditation-and-hindu-blessing-in-bali-indonesia?ref=6273",
    partner: "bookyogaretreats",
    bullets: [
      "Wellness, yoga, detox, spa, and meditation",
      "Hindu blessing — confirm schedule on listing",
      "Details on BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-de-moksha-5-eco-luxury",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "bali",
    country: "Indonesia",
    title: "5-day eco-luxury culture, yoga & meditation retreat",
    organizer: "De Moksha Boutique Resort & Restaurant",
    location: "Bali",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Resort and nature in Bali",
    href: "https://www.bookyogaretreats.com/de-moksha-boutique-resort-restaurant/5-day-eco-luxury-culture-yoga-and-meditation-retreat-in-bali?ref=6273",
    partner: "bookyogaretreats",
    bullets: [
      "Eco-luxury · culture, yoga, meditation",
      "Boutique resort — see room types on listing",
      "Book via BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-balitrees-4-culture-spa",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "bali",
    country: "Indonesia",
    title: "4-day yoga, culture, touring, spa & sound healing",
    organizer: "Balitrees Retreats",
    location: "Bali",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Rice fields and tropical landscape in Bali",
    href: "https://www.bookyogaretreats.com/balitrees-retreats/4-days-yoga-culture-touring-spa-sound-healing-purification-shamanic-blessing-in-bali?ref=6273",
    partner: "bookyogaretreats",
    bullets: [
      "Yoga, culture, spa, sound healing, purification, shamanic blessing",
      "Four-day format — full itinerary on listing",
      "Confirm on BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-baligrass-3-meditation",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "bali",
    country: "Indonesia",
    title: "3-day meditation & yoga retreat",
    organizer: "Baligrass Retreats",
    location: "Bali",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Quiet space for meditation in Bali",
    href: "https://www.bookyogaretreats.com/baligrass-retreats/3-days-meditation-and-yoga-retreats-in-bali-indonesia?ref=6273",
    partner: "bookyogaretreats",
    bullets: [
      "Short meditation and yoga immersion",
      "Indonesia — see venue on listing",
      "Book via BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-antharyamin-kerala-8",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "kerala",
    country: "India",
    title: "8-day yoga & Ayurveda retreat",
    organizer: "Antharyamin Resorts",
    location: "Kerala",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Backwaters and palms in Kerala",
    href: "https://www.bookyogaretreats.com/antharyamin-resorts/8-day-yoga-and-ayurveda-retreat-in-kerala?ref=6273",
    partner: "bookyogaretreats",
    bullets: [
      "Yoga and Ayurveda in Kerala",
      "Eight-day format — treatments on listing",
      "Details on BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-veda5-rishikesh-21-panchakarma",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "rishikesh",
    country: "India",
    title: "21-day Veda5 Panchakarma & authentic Ayurveda retreat",
    organizer: "Veda5 Ayurveda & Yoga Retreat",
    location: "Rishikesh",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Himalayan foothills and river near Rishikesh",
    href: "https://www.bookyogaretreats.com/veda5-ayurveda-yoga-retreat/21-day-veda5-authentic-ayurveda-panchakarma-treatments-and-retreat-in-rishikesh?ref=6273",
    partner: "bookyogaretreats",
    bullets: [
      "Extended Panchakarma and Ayurveda program",
      "Rishikesh — confirm medical intake on listing",
      "Book via BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-antharyamin-kerala-14",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "kerala",
    country: "India",
    title: "14-day yoga & Ayurveda retreat",
    organizer: "Antharyamin Resorts",
    location: "Kerala",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Calm tropical landscape in Kerala",
    href: "https://www.bookyogaretreats.com/antharyamin-resorts/14-day-yoga-and-ayurveda-retreat-in-kerala?ref=6273",
    partner: "bookyogaretreats",
    bullets: [
      "Two-week yoga and Ayurveda immersion",
      "Kerala — see treatment plan on listing",
      "Confirm on BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-antharyamin-kerala-20",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "kerala",
    country: "India",
    title: "20-day yoga & Ayurveda retreat",
    organizer: "Antharyamin Resorts",
    location: "Kerala",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Peaceful resort setting in Kerala",
    href: "https://www.bookyogaretreats.com/antharyamin-resorts/20-day-yoga-and-ayurveda-retreat-in-kerala-india?ref=6273",
    partner: "bookyogaretreats",
    bullets: [
      "Long-form yoga and Ayurveda stay",
      "Kerala — confirm length and inclusions on listing",
      "Details on BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-om-yoga-dharamsala-8",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "dharamsala",
    country: "India",
    title: "8-day yoga & meditation retreat",
    organizer: "Om Yoga Ashram",
    location: "Dharamsala, Himachal Pradesh",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Mountain air and forest near Dharamsala",
    href: "https://www.bookyogaretreats.com/om-yoga-ashram/8-day-yoga-meditation-retreat-in-dharamsala-himachal-pradesh-india?ref=6273",
    partner: "bookyogaretreats",
    bullets: [
      "Yoga and meditation in the Himalayas",
      "Dharamsala area — see ashram details on listing",
      "Book via BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-happiness-safari-bikram-coast-7",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "portugal-coast",
    country: "Portugal",
    title: "7-day Bikram yoga & wellness retreat (coast)",
    organizer: "Happiness Safari",
    location: "Portugal's coast",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Atlantic coastline in Portugal",
    href: "https://www.bookyogaretreats.com/happiness-safari/7-day-bikram-yoga-and-wellness-retreat-on-portugal-s-coast?ref=6273",
    partner: "bookyogaretreats",
    bullets: [
      "Bikram yoga and wellness · coastal Portugal",
      "Confirm exact base town on listing",
      "Details on BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-moka-ericeira-4-yoga",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "ericeira",
    country: "Portugal",
    title: "4-day rejuvenating yoga retreat",
    organizer: "Moka Surfhouse & Yoga Retreat",
    location: "Ericeira (Lisbon area)",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Surf town cliffs and ocean at Ericeira",
    href: "https://www.bookyogaretreats.com/moka-surfhouse-yoga-retreat/4-day-rejuvenating-yoga-retreat-in-ericeira-lisbon?ref=6273",
    partner: "bookyogaretreats",
    bullets: [
      "Short rejuvenating yoga stay",
      "Ericeira / Lisbon coast — see listing for surf option",
      "Book via BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-star-pine-portugal-5-budget",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "portugal",
    country: "Portugal",
    title: "5-day budget yoga retreat",
    organizer: "Star Pine Lodge",
    location: "Portugal",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Forest and quiet lodge setting in Portugal",
    href: "https://www.bookyogaretreats.com/star-pine-lodge/5-days-budget-yoga-retreat-in-portugal-1?ref=6273",
    partner: "bookyogaretreats",
    bullets: [
      "Budget-friendly five-day yoga retreat",
      "Confirm location and transfers on listing",
      "Details on BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-bron-aljezur-7-ayahuasca-equine",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "aljezur",
    country: "Portugal",
    title: "7-day ayahuasca, equine therapy & yoga holiday",
    organizer: "Bron voor Rust & Geluk",
    location: "Aljezur, Faro (Algarve)",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Rolling hills and coast in the Algarve",
    href: "https://www.bookyogaretreats.com/bron-voor-rust-geluk/7-day-ayahuasca-equine-therapy-and-yoga-holiday-in-aljezur-faro?ref=6273",
    partner: "bookyogaretreats",
    bullets: [
      "Ayahuasca, equine therapy, and yoga — read safety and eligibility on listing",
      "Aljezur area — Algarve",
      "Serious preparation required — confirm on BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-agadir-ranch-8-yoga-equestrian",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "agadir",
    country: "Morocco",
    title: "8-day all-inclusive yoga & equestrian vacation (ocean-facing riad, hammam)",
    organizer: "Agadir Ranch",
    location: "Near Agadir",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Atlantic coast and Moroccan landscape near Agadir",
    href: "https://www.bookyogaretreats.com/agadir-ranch/8-day-all-inclusive-yoga-and-equestrian-vacation-in-an-ocean-facing-riad-with-hammam-near-agadir?ref=6273",
    partner: "bookyogaretreats",
    bullets: [
      "Yoga, horses, hammam · ocean-facing riad",
      "All-inclusive — confirm riding level on listing",
      "Details on BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-nella-marrakech-6-yoga-culture",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "marrakech",
    country: "Morocco",
    title: "6-day immersive yoga & culture holiday",
    organizer: "Nella Retreats",
    location: "Marrakech",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Marrakech medina colours and architecture",
    href: "https://www.bookyogaretreats.com/nella-retreats/6-day-immersive-yoga-and-culture-holiday-in-marrakech?ref=6273",
    partner: "bookyogaretreats",
    bullets: [
      "Yoga and culture immersion in Marrakech",
      "Six days — see itinerary on listing",
      "Book via BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-salama-atlas-8-yoga",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "atlas-mountains-morocco",
    country: "Morocco",
    title: "8-day body, mind awareness & yoga retreat (Atlas Mountains)",
    organizer: "Salama Ayurveda",
    location: "Atlas Mountains",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "High Atlas valleys and mountain light in Morocco",
    href: "https://www.bookyogaretreats.com/salama-ayurveda/8-days-body-mind-awareness-and-yoga-retreat-in-the-atlas-mountains-morocco?ref=6273",
    partner: "bookyogaretreats",
    bullets: [
      "Body–mind awareness and yoga in the Atlas",
      "Eight days — confirm transfers on listing",
      "Details on BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-nella-marrakech-5-yoga-culture",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "marrakech",
    country: "Morocco",
    title: "5-day yoga & culture retreat",
    organizer: "Nella Retreats",
    location: "Marrakech",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Courtyard and tiles in Marrakech",
    href: "https://www.bookyogaretreats.com/nella-retreats/5-day-yoga-and-culture-retreat-in-the-heart-of-marrakech?ref=6273",
    partner: "bookyogaretreats",
    bullets: [
      "Heart of Marrakech · yoga and culture",
      "Five-day format — see inclusions on listing",
      "Confirm on BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-riad-dar-zitoun-marrakech-6",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "marrakech",
    country: "Morocco",
    title: "6-day yoga & wellness holiday",
    organizer: "Riad Dar Zitoun",
    location: "Marrakech",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Traditional riad courtyard in Morocco",
    href: "https://www.bookyogaretreats.com/riad-dar-zitoun/6-day-yoga-and-wellness-holiday-in-marrakech-morocco?ref=6273",
    partner: "bookyogaretreats",
    bullets: [
      "Yoga and wellness in a Marrakech riad",
      "Six days — room types on listing",
      "Book via BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-bliss-tenerife-6-luxury",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "tenerife",
    country: "Spain",
    title: "6-day luxury yoga retreat with island excursions",
    organizer: "Bliss Yoga Retreats Tenerife",
    location: "Tenerife",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Volcanic coast and ocean on Tenerife",
    href: "https://www.bookyogaretreats.com/bliss-yoga-retreats-tenerife/6-day-luxury-yoga-retreat-with-free-island-excursions-and-on-the-sunny-island-of-tenerife-spain?ref=6273",
    partner: "bookyogaretreats",
    bullets: [
      "Luxury yoga week · included island excursions",
      "Canary Islands sunshine — see schedule on listing",
      "Details on BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-sun-salute-torre-yoga-sculpt-5",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "torre-de-la-horadada",
    country: "Spain",
    title: "5-day yoga sculpt retreat",
    organizer: "Sun Salute Retreats",
    location: "Torre de la Horadada, Valencian Community",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Mediterranean light on the Costa Blanca",
    href: "https://www.bookyogaretreats.com/sun-salute-retreats/5-day-yoga-sculpt-retreat-in-sunny-torre-de-la-horadada-valencian-community?ref=6273",
    partner: "bookyogaretreats",
    bullets: [
      "Yoga sculpt focus · Torre de la Horadada",
      "Five days — confirm intensity on listing",
      "Book via BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-sun-salute-alicante-week-bnb",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "alicante",
    country: "Spain",
    title: "1-week yoga bed & breakfast holiday",
    organizer: "Sun Salute Retreats",
    location: "Alicante",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Coastal city and sea near Alicante",
    href: "https://www.bookyogaretreats.com/sun-salute-retreats/1-week-yoga-bed-and-breakfast-holiday-in-alicante-spain?ref=6273",
    partner: "bookyogaretreats",
    bullets: [
      "Week-long B&B yoga format",
      "Alicante — see accommodation on listing",
      "Details on BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-sun-salute-alicante-sun-beach-5",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "alicante",
    country: "Spain",
    title: "5-day sun & beach yoga holiday",
    organizer: "Sun Salute Retreats",
    location: "Alicante",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Beach and Mediterranean in Alicante province",
    href: "https://www.bookyogaretreats.com/sun-salute-retreats/5-day-sun-and-beach-yoga-holiday-in-alicante-spain?ref=6273",
    partner: "bookyogaretreats",
    bullets: [
      "Sun and beach yoga · five days",
      "Costa Blanca — confirm base on listing",
      "Confirm on BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-essence-arenal-7-rainforest",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "arenal-costa-rica",
    country: "Costa Rica",
    title: "7-day rainforest yoga holiday",
    organizer: "Essence Arenal Wellness Center",
    location: "El Castillo, Alajuela",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Rainforest canopy and mist near Arenal",
    href: "https://www.bookyogaretreats.com/essence-arenal-wellness-center/7-day-rainforest-yoga-holiday-in-el-castillo-alajuela-province?ref=6273",
    partner: "bookyogaretreats",
    bullets: [
      "Rainforest yoga · Arenal area",
      "Seven days — see lodge details on listing",
      "Book via BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-ashtanga-mama-guanacaste-6",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "guanacaste",
    country: "Costa Rica",
    title: "6-day tailored luxury yoga & mindfulness retreat",
    organizer: "Ashtanga Yoga Mama",
    location: "Playa Azul, Guanacaste",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Pacific coast jungle and beach in Guanacaste",
    href: "https://www.bookyogaretreats.com/ashtanga-yoga-mama/6-day-tailored-luxury-yoga-and-mindfulness-retreat-in-playa-azul-guanacaste?ref=6273",
    partner: "bookyogaretreats",
    bullets: [
      "Tailored luxury yoga and mindfulness",
      "Playa Azul — confirm group size on listing",
      "Details on BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-essence-arenal-4-rainforest",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "arenal-costa-rica",
    country: "Costa Rica",
    title: "4-day rainforest yoga retreat",
    organizer: "Essence Arenal Wellness Center",
    location: "El Castillo",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Tropical forest near Arenal volcano",
    href: "https://www.bookyogaretreats.com/essence-arenal-wellness-center/4-day-rainforest-yoga-retreat-in-el-castillo?ref=6273",
    partner: "bookyogaretreats",
    bullets: [
      "Short rainforest yoga immersion",
      "El Castillo — Essence Arenal",
      "Confirm on BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-essence-arenal-7-love-yourself",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "arenal-costa-rica",
    country: "Costa Rica",
    title: '7-day "Love Yourself" retreat (Arenal rainforest)',
    organizer: "Essence Arenal Wellness Center",
    location: "Arenal rainforest",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Lush rainforest and wellness space in Costa Rica",
    href: "https://www.bookyogaretreats.com/essence-arenal-wellness-center/7-days-love-yourself-retreat-in-the-arenal-rainforest-costa-rica?ref=6273",
    partner: "bookyogaretreats",
    bullets: [
      "Week-long self-care retreat in the rainforest",
      "Arenal area — see program on listing",
      "Book via BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
  {
    id: "bookyoga-essence-arenal-7-detox-yoga",
    category: "yoga",
    retreatTypes: ["yoga-retreat"],
    regionSlug: "arenal-costa-rica",
    country: "Costa Rica",
    title: "7-day detox & yoga holiday",
    organizer: "Essence Arenal Wellness Center",
    location: "Arenal, Alajuela",
    coverImage: "/retreats/bookyoga-placeholder.jpg",
    coverImageAlt: "Volcano and jungle near Arenal",
    href: "https://www.bookyogaretreats.com/essence-arenal-wellness-center/7-day-detox-and-yoga-holiday-in-arenal-alajuela-costa-rica?ref=6273",
    partner: "bookyogaretreats",
    bullets: [
      "Detox and yoga in the Arenal region",
      "Seven days — confirm protocols on listing",
      "Details on BookYogaRetreats",
    ],
    priceNote: "Confirm pricing on BookYogaRetreats.",
  },
];

export const RETREAT_TYPE_LABELS: Record<RetreatTypeFacet, string> = {
  "surf-camp": "Surf camp",
  "surf-yoga": "Surf + yoga",
  kitesurf: "Kitesurf",
  "yoga-retreat": "Yoga retreat",
};

export const RETREAT_CATEGORY_LABELS: Record<RetreatCategory, string> = {
  surf: "Surfing",
  yoga: "Yoga",
};

export const REGION_LABELS: Record<string, string> = {
  "imi-ouaddar": "Imi Ouaddar / Taghazout area",
  tamraght: "Tamraght",
  essaouira: "Essaouira area",
  porto: "Porto (North Portugal)",
  peniche: "Peniche",
  oahu: "Oahu, Hawaii",
  lagos: "Lagos",
  "porto-beach": "Porto beach area",
  weligama: "Weligama",
  cabarete: "Cabarete",
  "santa-cruz-pt": "Santa Cruz (Portugal)",
  agadir: "Agadir area",
  "ovar-aveiro": "Ovar / Aveiro, Portugal",
  "taghazout-region": "Taghazout region",
  sedona: "Sedona, USA",
  alicante: "Alicante / Costa Blanca",
  goa: "Goa",
  bali: "Bali",
  kampot: "Kampot",
  vallemaggia: "Vallemaggia, Switzerland",
  "peneda-geres": "Peneda-Gerês, Portugal",
  "torre-de-la-horadada": "Torre de la Horadada, Spain",
  "ko-pha-ngan": "Koh Phangan, Thailand",
  phuket: "Phuket, Thailand",
  thailand: "Thailand",
  "nusa-lembongan": "Nusa Lembongan, Indonesia",
  kerala: "Kerala, India",
  rishikesh: "Rishikesh, India",
  dharamsala: "Dharamsala, India",
  "portugal-coast": "Portugal coast",
  ericeira: "Ericeira, Portugal",
  portugal: "Portugal",
  aljezur: "Aljezur, Algarve",
  marrakech: "Marrakech, Morocco",
  "atlas-mountains-morocco": "Atlas Mountains, Morocco",
  tenerife: "Tenerife, Spain",
  "arenal-costa-rica": "Arenal / El Castillo, Costa Rica",
  guanacaste: "Guanacaste, Costa Rica",
};

export function getDistinctRegionSlugs(listings: RetreatListing[]): string[] {
  const set = new Set(listings.map((l) => l.regionSlug));
  return [...set].sort();
}

export type RetreatFilters = {
  category: RetreatCategory | "all";
  typeFacet: RetreatTypeFacet | "all";
  regionSlug: string | "all";
  maxPriceEur: number | null;
};

export function filterRetreatCatalog(listings: RetreatListing[], f: RetreatFilters): RetreatListing[] {
  return listings.filter((l) => {
    if (f.category !== "all" && l.category !== f.category) return false;

    if (f.typeFacet !== "all" && !l.retreatTypes.includes(f.typeFacet)) return false;

    if (f.regionSlug !== "all" && l.regionSlug !== f.regionSlug) return false;

    if (f.maxPriceEur != null && f.maxPriceEur > 0) {
      if (l.priceFromEur != null && l.priceFromEur > f.maxPriceEur) return false;
    }

    return true;
  });
}
